### ISSUE TITLE
Expandable/Retractable Components in Course-Side

### ISSUE THREAD

**Issue by HPunktOchs** [utetrapp/geli#245]
# User Story

### As a: 
Student

### I want:
The several Components to be extendable/Retractable

### so that:
the Course Materials and Informatins look a lot more structured and organized.

## Acceptance criteria:
Make the Several Course Components Expandable/Retractable

**Comment by d89** [comment]
Looks good - one tiny improvement suggestion: Please deactivate the arrow or hide it alltogether, when there is no content in a lecture. In that case, toggling the arrow makes no sense because nothing actually changes in appearance.

![image](https://user-images.githubusercontent.com/423154/33340683-13d3ecc8-d47d-11e7-9df9-90a3816c3d72.png)

**Comment by PatrickSkowronek** [comment]
We display now a message that the box is empty! Closed!
