### ISSUE TITLE
🐛 BUG: Fix security leak: static upload path

### ISSUE THREAD

**Issue by PatrickSkowronek** [utetrapp/geli#729]
# User Story

Currently the `api/uploads` can be accessed without logging into geli. https://github.com/h-da/geli/blob/dd7dbd94fc08ab901376a1bd526cbd6cd044d6d1/api/src/server.ts#L58 This should be changed. 

- [x] Done: User must be logged in.
- [x] See ¹: The user has access to the course where the file is present.
- [x] See ¹: The file is present in a unit and not just in the media manager.

¹ @torss: These two aspects have not really been achieved (see the PR for details), but are to some degree already guaranteed thanks to the secret / randomized / unguessable filenames that `geli` employs. _(Unless I am severely mistaken that is.)_

**Comment by PatrickSkowronek** [comment]
@torss the first is a must! the rest will be a lot of work. What do you think?

**Comment by torss** [comment]
@PatrickSkowronek I can't say for sure right now, but I will try to get all of it done if possible.

**Comment by torss** [comment]
Alright, this definitely will need some front-end changes, because the authentication token needs to be sent somehow for e.g. profile images.

**Comment by torss** [comment]
So...the remaining problem for me is that I still haven't managed to figure out how to **properly** transmit the authentication token for `<img>` or `<video>` tags from the front-end: The requests for these are directly handled by the browser and it appears we simply cannot add our custom authorization headers (or anything else). _I've tried Angular's `HttpInterceptor` by the way, but that can't deal with this either, which of course makes sense if there truly is no way to modify these headers with common browser APIs._

For `<img>`s the not particularly elegant but acceptable solution is to request them separately, using e.g. the `getDownload` method of our `BackendService`, then use `URL.createObjectURL` to get an URL that can be used as the `src` for the `<img>`. As you can imagine, this seems less suitable for `<video>`s, and I suspect a solution in that direction would become needlessly complex.

Then I found [this](https://itnext.io/using-service-worker-as-an-auth-relay-5abc402878dd) which shows a way to use service workers as interceptors, who then should be able to add the authorization headers. However, besides that not being exactly too straightforward itself, Angular's built-in support for service workers apparently [does not work with `ng serve`](https://angular.io/guide/service-worker-getting-started#serving-with-http-server) - _probably since the service workers are only intended to serve as optional supplements for PWA offline functionality_.

With that said I now only know of two ways to solve this problem in a fairly elegant, uniform manner:
1. Use cookies to send the tokens. This should work with `<img>`s and `<video>`s I reckon, but CSRF must be mitigated somehow.
2. Send the token as an URL query parameter (at least/only for `<img>`s and`<video>`s). But I guess that leads to its own security issues as well.

I could really use help from someone more knowledgeable regarding this topic, so please chime in if you happen to know anything at all about this. ;)

**Comment by torss** [comment]
@PatrickSkowronek At the last meeting I consulted @Gargamil on this issue. One solution we came up with - and the one I now implemented - is to indeed send a token via URL query parameter. But not the regular user token that grants full access to the user-account's extent. Instead a special `'mediaToken'` is generated for this sole purpose. It can only request specific routes, i.e. the ones that serve files, such as those from the `'uploads'` route (images, videos, PDFs, ...). So no, `<img>` and `<video>` are no longer accessible without login! This solution has some positive side-effects that a theoretical stricter variant would not have permitted, but also some downsides. More in the upcoming PR.
